### ISSUE TITLE
IOS Issues

### ISSUE THREAD

**Issue by mohamedkhabir12** [BisoDevil/TelrFlutter#1]
in ios the execution gives me :
unable to open file (in target "Runner" in project "Runner") (in target 'Runner' from project 'Runner')

**Comment by BisoDevil** [comment]
> in ios the execution gives me :
> unable to open file (in target "Runner" in project "Runner") (in target 'Runner' from project 'Runner')

did you run  ``` pod update``` in terminal

**Comment by mohamedkhabir12** [comment]
yes but the same i use xcode 12.4

**Comment by mohamedkhabir12** [comment]
please i need a solution , thank you

**Comment by mohamedkhabir12** [comment]
Xcode's output:
↳
    /Users/macbook/.pub-cache/hosted/pub.dartlang.org/telr_flutter-0.0.1/ios/Classes/SwiftTelrFlutterPlugin.swift:3:8: error: module compiled with Swift 5.3 cannot be imported by the Swift 5.2.4 compiler: /Users/macbook/Downloads/noor-app-v1-telr_payment_gateway/ios/.symlinks/plugins/telr_flutter/ios/TelrSDK.framework/Modules/TelrSDK.swiftmodule/x86_64.swiftmodule
    import TelrSDK
           ^
    /Users/macbook/.pub-cache/hosted/pub.dartlang.org/telr_flutter-0.0.1/ios/Classes/SwiftTelrFlutterPlugin.swift:3:8: error: module compiled with Swift 5.3 cannot be imported by the Swift 5.2.4 compiler: /Users/macbook/Downloads/noor-app-v1-telr_payment_gateway/ios/.symlinks/plugins/telr_flutter/ios/TelrSDK.framework/Modules/TelrSDK.swiftmodule/x86_64.swiftmodule
    import TelrSDK
           ^
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro.


this is the new issus

**Comment by BisoDevil** [comment]
This is a known issue from native Telr SDK till i fix it you can use xcode 12.0 so you can proceed sorry for that 
This plugin was made for personal use

**Comment by mohamedkhabir12** [comment]
ok thanks a lot
